[package]
name = "lightning_bolt"
version = "1.0.0"
edition = "2021"

[profile.dev]
panic="abort"

[profile.release]
panic="abort"

[dependencies]
bootloader="0.9"
spin = "0.5.2"
volatile = "0.2.3"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]